/// Flutter icons SearchIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SearchIcons
///      fonts:
///       - asset: fonts/SearchIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SearchIcons {
  SearchIcons._();

  static const _kFontFam = 'SearchIcons';
  static const String? _kFontPkg = null;

  static const IconData search =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
