/// Flutter icons SettingsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SettingsIcons
///      fonts:
///       - asset: fonts/SettingsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SettingsIcons {
  SettingsIcons._();

  static const _kFontFam = 'SettingsIcons';
  static const String? _kFontPkg = null;

  static const IconData dialog = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
